<?php
// -----
// Part of the One-Page Checkout plugin, provided under GPL 2.0 license by lat9 (cindy@vinosdefrutastropicales.com).
// Copyright (C) 2017-2022, Vinos de Frutas Tropicales.  All rights reserved.
//
// This module is included by tpl_modules_opc_billing_address.php and tpl_modules_opc_shipping_address.php and
// provides a common-formatting for those two address-blocks.
//
// Modified for use by the 'bootstrap' template:  Bootstrap/OPC v1.0.4
//
?>
<!--bof address block -->
<?php
// -----
// Sanitize module input values.
//
if (!isset($opc_address_type) || !in_array($opc_address_type, ['bill', 'ship'])) {
    trigger_error("Unknown value for opc_address_type ($opc_address_type).", E_USER_ERROR);
    exit();
}

// -----
// Start address formatting ...
//
$which = $opc_address_type;
$address = $_SESSION['opc']->getAddressValues($which);
if ($address['validated']) {
    $display_condensed_address = true;
    $address_form_class = ' class="hiddenField"';
} else {
    $display_condensed_address = false;
    $address_form_class = '';
}

$_SESSION['opc_addr_block_address'] = $address;

// -----
// Create a variable that can be used in all form-entry fields below to add a clearing break to the display.
//
// Note: For the bootstrap template's use, we'll turn this into a simply spacing div.
//
$clear_both = '<div class="p-2"></div>';

// -----
// Indicate that the default parameters to apply to each label generated by $_SESSION['opc']->formatAddressEntry()
// should be ' class="inputLabel"', unless otherwise overridden.
//
$_SESSION['opc']->setAddressLabelParams(' class="inputLabel"');
// -----
// The first section of an address-block contains the condensed formatting of the address, to reduce
// on-screen real-estate required.
//
if ($display_condensed_address) {
?>
<div id="address-<?php echo $which; ?>" class="row">
    <div class="col-10"><?php echo zen_address_format(zen_get_address_format_id($address['country_id']), $address, true, '', '<br>'); ?></div>
<?php
if (!$opc_disable_address_change) {
?>
    <div class="text-right" id="opc-<?php echo $which; ?>-edit"><?php echo zen_image_button(BUTTON_IMAGE_EDIT_SMALL, BUTTON_EDIT_SMALL_ALT); ?></div>
<?php
}
?>
</div>
<?php
}

// -----
// The second section contains the address-form through which an address can be changed, if enabled.  If the
// address can't be changed, perform a quick return so that the form elements aren't rendered.
//
if ($opc_disable_address_change) {
    return;
}
?>
<div id="address-form-<?php echo $which; ?>"<?php echo $address_form_class; ?>>
<?php
// -----
// If the address can be changed and an account-bearing customer has previously-defined addresses, create a dropdown list
// from which they can select.
//
// Note: Checking for more than two (2) entries, since the "Choose from previous selections" is
// pre-populated!
//
if (!$opc_disable_address_change) {
    $address_selections = $_SESSION['opc']->formatAddressBookDropdown();
    if (count($address_selections) > 2) {
        $selected = $_SESSION['opc']->getAddressDropDownSelection($which);
?>
    <div id="choices-<?php echo $which; ?>"><?php echo zen_draw_pull_down_menu("address-$which", $address_selections, $selected); ?></div>
<?php
    }
}
?>
    <h4>Please select an ordering unit.</h4><br>
<?php
$field_name = "firstname[$which]";
$field_id = "firstname-$which";
?>
    <input type="hidden" id="<?php echo $field_id; ?>" name="<?php echo $field_name; ?>" value="<?php echo $address['firstname'];?>" />
    <?php

$field_name = "lastname[$which]";
$field_id = "lastname-$which";
?>
    <input type="hidden" id="<?php echo $field_id; ?>" name="<?php echo $field_name; ?>" value="<?php echo $address['lastname'];?>" />
    <?php

$field_name = "company[$which]";
$field_id = "company-$which";
?>
    <input type="hidden" id="<?php echo $field_id; ?>" name="<?php echo $field_name; ?>" value="<?php echo $address['company'];?>" />
<?php
$agency = $_SESSION['IEMS']['customer_agency_code'];
$field_name = "agency[$which]";
$field_id = "agency-$which";?>
<input type="hidden" id="<?php echo $field_id; ?>" name="<?php echo $field_name; ?>" value="<?php echo $agency;?>" />
<?php

$field_name = "unit[$which]";
$field_id = "unit-$which";?>
<label class="inputLabel" for="<?php echo $field_id; ?>"><?php echo ENTRY_UNIT; ?></label><br>
<?php
// IEMS EDITED CODE //

filtered_unit_lookup($agency);
echo zen_draw_pull_down_menu($field_name, $filtered_unit_array, $address['unit'], "id=\"$field_id\" class=\"col-md-5\"") . (zen_not_null(ENTRY_UNIT_TEXT) ? '<span class="alert">' . ENTRY_UNIT_TEXT . '</span>' : '') .
    $clear_both;;?>
<?php
// END IEMS EDITED CODE //

$field_name = "zone_country_id[$which]";
$field_id = "country-$which";
?>
      <label class="inputLabel" for="<?php echo $field_id; ?>"><?php echo ENTRY_COUNTRY; ?></label><br>
      <?php echo zen_get_country_list($field_name, $address['country'], "id=\"$field_id\"") .
      (zen_not_null(ENTRY_COUNTRY_TEXT) ? '<span class="alert">' . ENTRY_COUNTRY_TEXT . '</span>' : '') .
$clear_both;

$field_name = "street_address[$which]";
$field_id = "street_address-$which";
?>
    <input type="hidden" id="<?php echo $field_id; ?>" name="<?php echo $field_name; ?>" value="<?php echo $address['street_address'];?>" />
<?php
$field_name = "city[$which]";
$field_id = "city-$which";
?>
    <input type="hidden" id="<?php echo $field_id; ?>" name="<?php echo $field_name; ?>" value="<?php echo $address['city'];?>" />
<?php
$field_name = "postcode[$which]";
$field_id = "postcode-$which";
?>
    <input type="hidden" id="<?php echo $field_id; ?>" name="<?php echo $field_name; ?>" value="<?php echo $address['postcode'];?>" />
    <div id="messages-<?php echo $which; ?>" class="mt-2"></div>
</div>
<!--eof address block -->
